from tkinter import *

janela = Tk()
janela.title("Mercadinho_Do_Nordeste")
janela.geometry("320x480")

y = Label(janela, text= "=========MERCADINHO DO NORDESTE=========").place(x=5,y=10)
x = Label(janela, text="Código do produto: ").place(x=10,y=50)
pproduto = Entry(janela)
pproduto.place(x=130,y=50)

a = Label(janela, text= "=======================================").place(x=1,y=130)
b = Label(janela, text= "=======================================").place(x=1,y=370)
c = Label(janela, text= "=======================================").place(x=1,y=430)

produto = Label(janela, text="Produto: ").place(x=10, y = 150)
preço = Label(janela, text="Preço(U): ").place(x=10,y = 190)
preço = Label(janela, text="Preço(F/C): ").place(x=10,y = 230)
estoque = Label(janela, text="Estoque: ").place(x=10,y = 270)
setor = Label(janela, text="Setor: ").place(x=10,y = 310)

def imprimir_etiqueta():
    impressao = Label(janela,text="Impressão enviada").place(x=110,y=350)

bt2 = Button(janela, text= "Imprimir Etiqueta",command=imprimir_etiqueta).place(x=110,y=400)

def pesquisa_produto():
  pesquisa = pproduto.get()
  if pesquisa == "10001":
     limpar = Label(janela, text="                                    ").place(x=80, y=150)
     limpar = Label(janela, text="                                    ").place(x=80, y=190)
     limpar = Label(janela, text="                                    ").place(x=80, y=230)
     limpar = Label(janela, text="                                    ").place(x=80, y=270)
     limpar = Label(janela, text="                                    ").place(x=80, y=310)
     limpar = Label(janela, text="                                    ").place(x=110,y=350)
     coca = Label(janela,text= "Coca-Cola 2L").place(x=80, y = 150)
     coca = Label(janela, text=" R$ 6,99").place(x=80, y=190)
     coca = Label(janela, text="R$ 41,94(FD/6)").place(x=80, y=230)
     coca = Label(janela, text="500(FD").place(x=80, y=270)
     coca = Label(janela, text="Bebida").place(x=80, y=310)
  if pesquisa == "10002":
      limpar = Label(janela, text="                                                           ").place(x=80, y=150)
      limpar = Label(janela, text="                                                           ").place(x=80, y=190)
      limpar = Label(janela, text="                                                           ").place(x=80, y=230)
      limpar = Label(janela, text="                                                           ").place(x=80, y=270)
      limpar = Label(janela, text="                                                           ").place(x=80, y=310)
      limpar = Label(janela, text="                                                           ").place(x=110, y=350)
      fanta = Label(janela, text="Fanta 2L").place(x=80, y=150)
      fanta = Label(janela, text="R$ 5,69").place(x=80, y=190)
      fanta = Label(janela, text="R$ 34,14(FD/6)").place(x=80, y=230)
      fanta = Label(janela, text="450(FD)").place(x=80, y=270)
      fanta = Label(janela, text="Bebida").place(x=80, y=310)
  if pesquisa == "10003":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=80, y=310)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      brahma= Label(janela, text="Brahma 473ML").place(x=80, y=150)
      brahma = Label(janela, text="R$ 3,45").place(x=80, y=190)
      brahma = Label(janela, text="R$ 20,70(FD/6)").place(x=80, y=230)
      brahma = Label(janela, text="676(FD)").place(x=80, y=270)
      brahma = Label(janela, text="Bebida").place(x=80, y=310)
  if pesquisa == "10004":
      limpar = Label(janela, text="                                                           ").place(x=80, y=150)
      limpar = Label(janela, text="                                                           ").place(x=80, y=190)
      limpar = Label(janela, text="                                                           ").place(x=80, y=230)
      limpar = Label(janela, text="                                                           ").place(x=80, y=270)
      limpar = Label(janela, text="                                                           ").place(x=80, y=310)
      limpar = Label(janela, text="                                                           ").place(x=110, y=350)
      heineken = Label(janela, text="Heineken 330ML").place(x=80, y=150)
      heineken = Label(janela, text="R$ 4,69").place(x=80, y=190)
      heineken = Label(janela, text="R$ 28,14(FD/6)").place(x=80, y=230)
      heineken = Label(janela, text="456(FD)").place(x=80, y=270)
      heineken = Label(janela, text="Bebida").place(x=80, y=310)
  if pesquisa == "10005":
      limpar = Label(janela, text="                                                           ").place(x=80, y=150)
      limpar = Label(janela, text="                                                           ").place(x=80, y=190)
      limpar = Label(janela, text="                                                           ").place(x=80, y=230)
      limpar = Label(janela, text="                                                           ").place(x=80, y=270)
      limpar = Label(janela, text="                                                           ").place(x=80, y=310)
      limpar = Label(janela, text="                                                           ").place(x=110, y=350)
      redbull = Label(janela, text="Red Bull 250ML").place(x=80, y=150)
      redbull = Label(janela, text="R$ 5,69").place(x=80, y=190)
      redbull = Label(janela, text="R$ 34,14(FD/6)").place(x=80, y=230)
      redbull = Label(janela, text="150(FD)").place(x=80, y=270)
      redbull = Label(janela, text="Bebida").place(x=80, y=310)
  if pesquisa == "10006":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=80, y=310)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      monster = Label(janela, text="Monster Energy 473ML").place(x=80, y=150)
      monster = Label(janela, text="R$ 6,49 ").place(x=80, y=190)
      monster = Label(janela, text="R$ 38,94(FD/6)").place(x=80, y=230)
      monster = Label(janela, text="87(FD)").place(x=80, y=270)
      monster = Label(janela, text="Bebida").place(x=80, y=310)
  if pesquisa == "10007":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=80, y=310)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      kapo = Label(janela, text="Kapo 200ML").place(x=80, y=150)
      kapo = Label(janela, text="R$ 1,75 ").place(x=80, y=190)
      kapo = Label(janela, text="R$ 21,00(C/12)").place(x=80, y=230)
      kapo = Label(janela, text="167(CX)").place(x=80, y=270)
      kapo = Label(janela, text="Bebida").place(x=80, y=310)
  if pesquisa == "10008":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=80, y=310)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      toddynho = Label(janela, text="Toddynho 200ML").place(x=80, y=150)
      toddynho = Label(janela, text="R$ 1,98").place(x=80, y=190)
      toddynho = Label(janela, text="R$ 53,46(C/27)").place(x=80, y=230)
      toddynho = Label(janela, text="147(CX)").place(x=80, y=270)
      toddynho = Label(janela, text="Bebida").place(x=80, y=310)
  if pesquisa == "10009":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=80, y=310)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      vinho = Label(janela, text="Vinho Tinto Baron").place(x=80, y=150)
      vinho = Label(janela, text="R$ 34,90").place(x=80, y=190)
      vinho = Label(janela, text="R$ 320,76(C/6)").place(x=80, y=230)
      vinho = Label(janela, text="7(CX)").place(x=80, y=270)
      vinho = Label(janela, text="Bebida").place(x=80, y=310)
  if pesquisa == "10010":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=80, y=310)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      champagne = Label(janela, text="Champagne Chandon 750ML").place(x=80, y=150)
      champagne = Label(janela, text="R$ 72,90").place(x=80, y=190)
      champagne = Label(janela, text="R$ 437,40(C/6)").place(x=80, y=230)
      champagne = Label(janela, text="3(CX)").place(x=80, y=270)
      champagne = Label(janela, text="Bebida").place(x=80, y=310)
  if pesquisa == "11001":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=80, y=310)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      dove = Label(janela, text="Desodorante Dove 150ML").place(x=80, y=150)
      dove = Label(janela, text="R$ 8,50").place(x=80, y=190)
      dove = Label(janela, text="R$ 102,00(C/12)").place(x=80, y=230)
      dove = Label(janela, text="24(CX)").place(x=80, y=270)
      dove = Label(janela, text="Higiene Pessoal").place(x=80, y=310)
  if pesquisa == "11002":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=80, y=310)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      rexona = Label(janela, text="Desodorante Rexona 150ML").place(x=80, y=150)
      rexona = Label(janela, text="R$ 7,99").place(x=80, y=190)
      rexona = Label(janela, text="R$ 95,88(C/12), R$ 383,52").place(x=80, y=230)
      rexona = Label(janela, text="15CX)").place(x=80, y=270)
      rexona = Label(janela, text="Higiene Pessoal").place(x=80, y=310)

  if pesquisa =="11003":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=80, y=310)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      colgate = Label(janela, text="Creme dental Colgate 140g").place(x=80, y=150)
      colgate = Label(janela, text="R$ 8,29").place(x=80, y=190)
      colgate = Label(janela, text="R$ 99,48(F/12) == R$ 397,22(C/48)").place(x=80, y=230)
      colgate = Label(janela, text="13(CX)").place(x=80, y=270)
      colgate = Label(janela, text="Higiene Pessoal").place(x=80, y=310)
  if pesquisa == "11004":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=80, y=310)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      colgate = Label(janela, text="Creme dental Oral-B 140g").place(x=80, y=150)
      colgate = Label(janela, text="R$ 5,65").place(x=80, y=190)
      colgate = Label(janela, text="R$ 67,80(F/12) == R$ 271,20 (C/48)").place(x=80, y=230)
      colgate = Label(janela, text="17(CX)").place(x=80, y=270)
      colgate = Label(janela, text="Higiene Pessoal").place(x=80, y=310)
  if pesquisa == "11005":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=80, y=310)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      protex = Label(janela, text="Sabonete Protex 90g").place(x=80, y=150)
      protex = Label(janela, text="R$ 2,49").place(x=80, y=190)
      protex = Label(janela, text="R$ 29,88(F/12) == R$ 119,52(C/48)").place(x=80, y=230)
      protex = Label(janela, text="13(CX)").place(x=80, y=270)
      protex = Label(janela, text="Higiene Pessoal").place(x=80, y=310)
  if pesquisa == "11006":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=80, y=310)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      even = Label(janela, text="Sabonete Protex 90g").place(x=80, y=150)
      even = Label(janela, text="R$ 1,20").place(x=80, y=190)
      even = Label(janela, text="R$ 14,40(F/12) == R$ 57,60(C/48)").place(x=80, y=230)
      even = Label(janela, text="23(CX)").place(x=80, y=270)
      even = Label(janela, text="Higiene Pessoal").place(x=80, y=310)




bt = Button(janela, text="Pesquisar",command=pesquisa_produto).place(x=130,y=80)


janela.mainloop()
