from tkinter import *

janela =Tk()
janela.title("Mercadinho_Do_Nordeste")
janela.geometry("320x480")
janela.configure(background="white")

y = Label(janela, text= "=========MERCADINHO DO NORDESTE=========",bg = "blue",fg= "white").place(x=5,y=10)
x = Label(janela, text="Código do produto: ").place(x=10,y=50)
pproduto = Entry(janela)
pproduto.place(x=130,y=50)

a = Label(janela, text= "=======================================",bg ="blue",fg="white").place(x=1,y=120)
b = Label(janela, text= "=======================================",bg ="blue",fg="white").place(x=1,y=370)
c = Label(janela, text= "=======================================",bg ="blue",fg="white").place(x=1,y=430)

produto = Label(janela, text="Produto: ").place(x=10, y = 150)
preco = Label(janela, text="Preço(U): ").place(x=10,y = 190)
fpreco = Label(janela, text="Preço(F/C): ").place(x=10,y = 230)
setor = Label(janela, text="Setor: ").place(x=10,y = 270)
estoque = Label(janela, text="Estoque: ").place(x=10,y = 310)

def imprimir_etiqueta():
    impressao = Label(janela,text="Impressão enviada",bg="blue",fg="white").place(x=110,y=350)

bt2 = Button(janela, text= "Imprimir Etiqueta",command=imprimir_etiqueta).place(x=110,y=400)

def pesquisa_produto():
  pesquisa = pproduto.get()
  if pesquisa == "10001":
     limpar = Label(janela, text="                                                              ").place(x=80, y=150)
     limpar = Label(janela, text="                                                              ").place(x=80, y=190)
     limpar = Label(janela, text="                                                              ").place(x=80, y=230)
     limpar = Label(janela, text="                                                              ").place(x=80, y=270)
     limpar = Label(janela, text="                                                              ").place(x=110,y=350)
     coca = Label(janela,text= "Coca-Cola 2L").place(x=80, y = 150)
     coca = Label(janela, text=" R$ 6,99").place(x=80, y=190)
     coca = Label(janela, text="R$ 41,94(FD/6)").place(x=80, y=230)
     coca = Label(janela, text="Bebida").place(x=80, y=270)
     coca = Label(janela, text="300(FD)").place(x=80,y=310)
  if pesquisa == "10002":
      limpar = Label(janela, text="                                                           ").place(x=80, y=150)
      limpar = Label(janela, text="                                                           ").place(x=80, y=190)
      limpar = Label(janela, text="                                                           ").place(x=80, y=230)
      limpar = Label(janela, text="                                                           ").place(x=80, y=270)
      limpar = Label(janela, text="                                                           ").place(x=110, y=350)
      fanta = Label(janela, text="Fanta 2L").place(x=80, y=150)
      fanta = Label(janela, text="R$ 5,69").place(x=80, y=190)
      fanta = Label(janela, text="R$ 34,14(FD/6)").place(x=80, y=230)
      fanta = Label(janela, text="Bebida").place(x=80, y=270)
      fanta = Label(janela, text="265(FD)").place(x=80, y=310)
  if pesquisa == "10003":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      brahma= Label(janela, text="Brahma 473ML").place(x=80, y=150)
      brahma = Label(janela, text="R$ 3,45").place(x=80, y=190)
      brahma = Label(janela, text="R$ 20,70(FD/6)").place(x=80, y=230)
      brahma = Label(janela, text="Bebida").place(x=80, y=270)
      brahma = Label(janela, text="454(FD)").place(x=80, y=310)
  if pesquisa == "10004":
      limpar = Label(janela, text="                                                           ").place(x=80, y=150)
      limpar = Label(janela, text="                                                           ").place(x=80, y=190)
      limpar = Label(janela, text="                                                           ").place(x=80, y=230)
      limpar = Label(janela, text="                                                           ").place(x=80, y=270)
      limpar = Label(janela, text="                                                           ").place(x=110, y=350)
      heineken = Label(janela, text="Heineken 330ML").place(x=80, y=150)
      heineken = Label(janela, text="R$ 4,69").place(x=80, y=190)
      heineken = Label(janela, text="R$ 28,14(FD/6)").place(x=80, y=230)
      heineken = Label(janela, text="Bebida").place(x=80, y=270)
      heineken = Label(janela, text="321(FD)").place(x=80, y=310)
  if pesquisa == "10005":
      limpar = Label(janela, text="                                                           ").place(x=80, y=150)
      limpar = Label(janela, text="                                                           ").place(x=80, y=190)
      limpar = Label(janela, text="                                                           ").place(x=80, y=230)
      limpar = Label(janela, text="                                                           ").place(x=80, y=270)
      limpar = Label(janela, text="                                                           ").place(x=110, y=350)
      redbull = Label(janela, text="Red Bull 250ML").place(x=80, y=150)
      redbull = Label(janela, text="R$ 5,69").place(x=80, y=190)
      redbull = Label(janela, text="R$ 34,14(FD/6)").place(x=80, y=230)
      redbull = Label(janela, text="Bebida").place(x=80, y=270)
      redbull = Label(janela, text="130(CX)").place(x=80, y=310)
  if pesquisa == "10006":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      monster = Label(janela, text="Monster Energy 473ML").place(x=80, y=150)
      monster = Label(janela, text="R$ 6,49 ").place(x=80, y=190)
      monster = Label(janela, text="R$ 38,94(FD/6)").place(x=80, y=230)
      monster = Label(janela, text="Bebida").place(x=80, y=270)
      monster = Label(janela, text="123(CX)").place(x=80, y=310)
  if pesquisa == "10007":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      kapo = Label(janela, text="Kapo 200ML").place(x=80, y=150)
      kapo = Label(janela, text="R$ 1,75 ").place(x=80, y=190)
      kapo = Label(janela, text="R$ 21,00(C/12)").place(x=80, y=230)
      kapo = Label(janela, text="Bebida").place(x=80, y=270)
      kapo = Label(janela, text="132(CX)").place(x=80, y=310)
  if pesquisa == "10008":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      toddynho = Label(janela, text="Toddynho 200ML").place(x=80, y=150)
      toddynho = Label(janela, text="R$ 1,98").place(x=80, y=190)
      toddynho = Label(janela, text="R$ 53,46(C/27)").place(x=80, y=230)
      toddynho = Label(janela, text="Bebida").place(x=80, y=270)
      toddynho = Label(janela, text="231(CX)").place(x=80, y=310)
  if pesquisa == "10009":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      vinho = Label(janela, text="Vinho Tinto Baron").place(x=80, y=150)
      vinho = Label(janela, text="R$ 34,90").place(x=80, y=190)
      vinho = Label(janela, text="R$ 320,76(C/6)").place(x=80, y=230)
      vinho = Label(janela, text="Bebida").place(x=80, y=270)
      vinho = Label(janela, text="3(CX)").place(x=80, y=310)
  if pesquisa == "10010":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      champagne = Label(janela, text="Champagne Chandon 750ML").place(x=80, y=150)
      champagne = Label(janela, text="R$ 72,90").place(x=80, y=190)
      champagne = Label(janela, text="R$ 437,40(C/6)").place(x=80, y=230)
      champagne = Label(janela, text="Bebida").place(x=80, y=270)
      champagne = Label(janela, text="4(CX)").place(x=80, y=310)
  if pesquisa == "11001":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      dove = Label(janela, text="Desodorante Dove 150ML").place(x=80, y=150)
      dove = Label(janela, text="R$ 8,50").place(x=80, y=190)
      dove = Label(janela, text="R$ 102,00(C/12)").place(x=80, y=230)
      dove = Label(janela, text="Higiene Pessoal").place(x=80, y=270)
      dove = Label(janela, text="30(CX)").place(x=80, y=310)
  if pesquisa == "11002":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      rexona = Label(janela, text="Desodorante Rexona 150ML").place(x=80, y=150)
      rexona = Label(janela, text="R$ 7,99").place(x=80, y=190)
      rexona = Label(janela, text="R$ 95,88(C/12), R$ 383,52").place(x=80, y=230)
      rexona = Label(janela, text="Higiene Pessoal").place(x=80, y=270)
      rexona = Label(janela, text="43(CX)").place(x=80, y=310)
  if pesquisa =="11003":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      colgate = Label(janela, text="Creme dental Colgate 140g").place(x=80, y=150)
      colgate = Label(janela, text="R$ 8,29").place(x=80, y=190)
      colgate = Label(janela, text="R$ 99,48(F/12) == R$ 397,22(C/48)").place(x=80, y=230)
      colgate = Label(janela, text="Higiene Pessoal").place(x=80, y=270)
      colgate = Label(janela, text="20(CX)").place(x=80, y=310)
  if pesquisa == "11004":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      oralb = Label(janela, text="Creme dental Oral-B 140g").place(x=80, y=150)
      oralb = Label(janela, text="R$ 5,65").place(x=80, y=190)
      oralb = Label(janela, text="R$ 67,80(F/12) == R$ 271,20 (C/48)").place(x=80, y=230)
      oralb = Label(janela, text="Higiene Pessoal").place(x=80, y=270)
      oralb = Label(janela, text="15(CX)").place(x=80, y=310)
  if pesquisa == "11005":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      protex = Label(janela, text="Sabonete Protex 90g").place(x=80, y=150)
      protex = Label(janela, text="R$ 2,49").place(x=80, y=190)
      protex = Label(janela, text="R$ 29,88(F/12) == R$ 119,52(C/48)").place(x=80, y=230)
      protex = Label(janela, text="Higiene Pessoal").place(x=80, y=270)
      coca = Label(janela, text="300(FD)").place(x=80, y=310)
  if pesquisa == "11006":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      even = Label(janela, text="Sabonete Protex 90g").place(x=80, y=150)
      even = Label(janela, text="R$ 1,20").place(x=80, y=190)
      even = Label(janela, text="R$ 14,40(F/12) == R$ 57,60(C/48)").place(x=80, y=230)
      even = Label(janela, text="Higiene Pessoal").place(x=80, y=270)
      coca = Label(janela, text="300(FD)").place(x=80, y=310)
  if pesquisa == "11007":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      seda = Label(janela, text="Shampoo Seda 325ML").place(x=80, y=150)
      seda = Label(janela, text="R$ 9,29").place(x=80, y=190)
      seda = Label(janela, text="R$ 111,48(C/12)").place(x=80, y=230)
      seda = Label(janela, text="Higiene Pessoal").place(x=80, y=270)
      seda = Label(janela, text="10(FD)").place(x=80, y=310)
  if pesquisa == "11008":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      pantene = Label(janela, text="Shampoo Pantene 400ML").place(x=80, y=150)
      pantene = Label(janela, text="R$ 19,30").place(x=80, y=190)
      pantene = Label(janela, text="R$ 231,60(F/12)").place(x=80, y=230)
      pantene = Label(janela, text="Higiene Pessoal").place(x=80, y=270)
      pantene = Label(janela, text="12(FD)").place(x=80, y=310)
  if pesquisa == "11009":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      personal = Label(janela, text="Frauda Personal Todos Tamanhos").place(x=80, y=150)
      personal = Label(janela, text="R$ 29,90").place(x=80, y=190)
      personal = Label(janela, text="R$ 86,40(F/6)").place(x=80, y=230)
      personal = Label(janela, text="Higiene Pessoal").place(x=80, y=270)
      personal = Label(janela, text="20(FD)").place(x=80, y=310)
  if pesquisa == "11010":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      cotidian = Label(janela, text="Frauda Geriátrica Cotidian 24UN").place(x=80, y=150)
      cotidian = Label(janela, text="R$ 36,90").place(x=80, y=190)
      cotidian = Label(janela, text="R$ 57,60(F/6)").place(x=80, y=230)
      cotidian = Label(janela, text="Higiene Pessoal").place(x=80, y=270)
      cotidian = Label(janela, text="13(FD)").place(x=80, y=310)
  if pesquisa == "12001":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      glorito = Label(janela, text="Água Sanitária Glorito 1L").place(x=80, y=150)
      glorito = Label(janela, text="R$ 1,15").place(x=80, y=190)
      glorito = Label(janela, text="R$ 13,8(C/12)").place(x=80, y=230)
      glorito = Label(janela, text="Limpeza").place(x=80, y=270)
      glorito = Label(janela, text="200(CX)").place(x=80, y=310)
  if pesquisa == "12002":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      brilux = Label(janela, text="Água Sanitária Brilux 1L").place(x=80, y=150)
      brilux = Label(janela, text="R$ 2,35").place(x=80, y=190)
      brilux= Label(janela, text="R$ 28,20(C/12)").place(x=80, y=230)
      brilux = Label(janela, text="Limpeza").place(x=80, y=270)
      brilux = Label(janela, text="70(CX)").place(x=80, y=310)
  if pesquisa == "12003":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      urca = Label(janela, text="Lava Roupa Urca 5L").place(x=80, y=150)
      urca = Label(janela, text="R$ 21,90").place(x=80, y=190)
      urca = Label(janela, text="R$ 43,80(C/2)").place(x=80, y=230)
      urca = Label(janela, text="Limpeza").place(x=80, y=270)
      urca = Label(janela, text="30(CX)").place(x=80, y=310)
  if pesquisa == "12004":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      downy = Label(janela, text="Lava Roupa Downy 3L").place(x=80, y=150)
      downy = Label(janela, text="R$ 32,90").place(x=80, y=190)
      downy= Label(janela, text="R$ 131,60 (C/4)").place(x=80, y=230)
      downy = Label(janela, text="Limpeza").place(x=80, y=270)
      downy = Label(janela, text="19(CX)").place(x=80, y=310)
  if pesquisa == "12005":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      ype = Label(janela, text="Lava Louça Ype 500ML").place(x=80, y=150)
      ype = Label(janela, text="R$ 1,90").place(x=80, y=190)
      ype = Label(janela, text="R$ 45,60(C/24)").place(x=80, y=230)
      ype = Label(janela, text="Limpeza").place(x=80, y=270)
      ype = Label(janela, text="27(CX)").place(x=80, y=310)
  if pesquisa == "12006":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      invictos = Label(janela, text="Lava Louça Invictos 500ML").place(x=80, y=150)
      invictos = Label(janela, text="R$ 1,15").place(x=80, y=190)
      invictos = Label(janela, text="R$ 27,60(C/24)").place(x=80, y=230)
      invictos = Label(janela, text="Limpeza").place(x=80, y=270)
      invictos = Label(janela, text="45(CX)").place(x=80, y=310)
  if pesquisa == "12007":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      omo = Label(janela, text="Detergente em Pó Omo 400gSachê").place(x=80, y=150)
      omo = Label(janela, text="R$ 5,19").place(x=80, y=190)
      omo = Label(janela, text="R$ 103,80(FD/20)").place(x=80, y=230)
      omo = Label(janela, text="Limpeza").place(x=80, y=270)
      omo = Label(janela, text="23(FD)").place(x=80, y=310)
  if pesquisa == "12008":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      btevi = Label(janela, text="Detergente em Pó Bem-Te-Vi 500g").place(x=80, y=150)
      btevi = Label(janela, text="R$ 2,25").place(x=80, y=190)
      btevi = Label(janela, text="R$ 58,50(FD/26)").place(x=80, y=230)
      btevi = Label(janela,text="Limpeza").place(x=80, y=270)
      btevi = Label(janela, text="102(FD)").place(x=80, y=310)
  if pesquisa == "12009":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      troia = Label(janela, text="Desinfetante Troia 1L").place(x=80, y=150)
      troia = Label(janela, text="R$ 22,80").place(x=80, y=190)
      troia = Label(janela, text="R$ (CX/12)").place(x=80, y=230)
      troia = Label(janela, text="Limpeza").place(x=80, y=270)
      troia = Label(janela, text="54(CX)").place(x=80, y=310)
  if pesquisa == "12010":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      pinho = Label(janela, text="Desinfetante Pinho Sol 1L").place(x=80, y=150)
      pinho = Label(janela, text="R$ 7,95").place(x=80, y=190)
      pinho = Label(janela, text="R$ 95,40(CX/12)").place(x=80, y=230)
      pinho = Label(janela, text="Limpeza").place(x=80, y=270)
      pinho = Label(janela, text="30(CX)").place(x=80, y=310)
  if pesquisa == "13001":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      pop = Label(janela, text="Arroz Pop 1K").place(x=80, y=150)
      pop = Label(janela, text="R$ 4,55").place(x=80, y=190)
      pop = Label(janela, text="R$ 45,50(FD/10)").place(x=80, y=230)
      pop = Label(janela, text="Básico").place(x=80, y=270)
      pop = Label(janela, text="120(FD)").place(x=80, y=310)
  if pesquisa == "13002":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      tio = Label(janela, text="Arroz Tio João 1K").place(x=80, y=150)
      tio = Label(janela, text="R$ 5,98").place(x=80, y=190)
      tio = Label(janela, text="R$ 58,80(FD/10)").place(x=80, y=230)
      tio = Label(janela, text="Básico").place(x=80, y=270)
      tio = Label(janela, text="112(FD)").place(x=80, y=310)
  if pesquisa == "13003":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      kicaldo = Label(janela, text="Feijão Kicaldo 1K").place(x=80, y=150)
      kicaldo = Label(janela, text="R$ 6,29").place(x=80, y=190)
      kicaldo = Label(janela, text="R$ 62,90(FD/10)").place(x=80, y=230)
      kicaldo = Label(janela, text="Básico").place(x=80, y=270)
      kicaldo = Label(janela, text="97(FD)").place(x=80, y=310)
  if pesquisa == "13004":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      turqueza = Label(janela, text="Feijão Turqueza 1K").place(x=80, y=150)
      turqueza = Label(janela, text="R$ 9,30").place(x=80, y=190)
      turqueza = Label(janela, text="R$ 93,00(FD/10)").place(x=80, y=230)
      turqueza = Label(janela, text="Básico").place(x=80, y=270)
      turqueza = Label(janela, text="99(FD)").place(x=80, y=310)
  if pesquisa == "13005":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      coringa = Label(janela, text="Flocão de Milho Coringa 500g").place(x=80, y=150)
      coringa = Label(janela, text="R$ 2,53").place(x=80, y=190)
      coringa = Label(janela, text="R$ 50,60(FD/20)").place(x=80, y=230)
      coringa = Label(janela, text="Básico").place(x=80, y=270)
      coringa = Label(janela, text="143(FD)").place(x=80, y=310)
  if pesquisa == "13006":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      marata = Label(janela, text="Flocão de Milho Maratá 500g").place(x=80, y=150)
      marata = Label(janela, text="R$ 1,69").place(x=80, y=190)
      marata = Label(janela, text="R$ 33,80(FD/20)").place(x=80, y=230)
      marata = Label(janela, text="Básico").place(x=80, y=270)
      marata = Label(janela, text="160(FD)").place(x=80, y=310)
  if pesquisa == "13007":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      kicaldo = Label(janela, text="Farinha de Mandioca Kicaldo 1K").place(x=80, y=150)
      kicaldo = Label(janela, text="R$ 3,89").place(x=80, y=190)
      kicaldo = Label(janela, text="R$ 38,90(FD/10)").place(x=80, y=230)
      kicaldo = Label(janela, text="Básico").place(x=80, y=270)
      kicaldo = Label(janela, text="67(FD)").place(x=80, y=310)
  if pesquisa == "13008":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      yoki = Label(janela, text="Farinha de Mandioca Yoki 1K").place(x=80, y=150)
      yoki = Label(janela, text="R$ 6,74").place(x=80, y=190)
      yoki = Label(janela, text="R$ 67,74(FD/10)").place(x=80, y=230)
      yoki = Label(janela, text="Básico").place(x=80, y=270)
      yoki = Label(janela, text="47(FD)").place(x=80, y=310)
  if pesquisa == "13009":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      uniao = Label(janela, text="Açúcar União 1K").place(x=80, y=150)
      uniao = Label(janela, text="R$ 3,08").place(x=80, y=190)
      uniao = Label(janela, text="R$ 30,80(FD/10)").place(x=80, y=230)
      uniao = Label(janela, text="Básico").place(x=80, y=270)
      uniao = Label(janela, text="92(FD)").place(x=80, y=310)
  if pesquisa == "13010":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      caravelas = Label(janela, text="Açúcar Caravelas 1K").place(x=80, y=150)
      caravelas = Label(janela, text="R$ 2,39").place(x=80, y=190)
      caravelas = Label(janela, text="R$ 23,90(FD/10)").place(x=80, y=230)
      caravelas = Label(janela, text="Básico").place(x=80, y=270)
      caravelas = Label(janela, text="103(FD)").place(x=80, y=310)
  if pesquisa == "14001":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      urbano = Label(janela, text="Macarrão Urbano Espaguete 500g").place(x=80, y=150)
      urbano = Label(janela, text="R$ 3,09").place(x=80, y=190)
      urbano = Label(janela, text="R$ 61,80(FD/10)").place(x=80, y=230)
      urbano = Label(janela, text="Massa/Molho").place(x=80, y=270)
      urbano = Label(janela, text="98(FD)").place(x=80, y=310)
  if pesquisa == "14002":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      vitarella = Label(janela, text="Massa de Lasanha Vitarella 500g").place(x=80, y=150)
      vitarella = Label(janela, text="R$ 6,99").place(x=80, y=190)
      vitarella = Label(janela, text="R$ 69,90(CX/10)").place(x=80, y=230)
      vitarella = Label(janela, text="Massa/Molho").place(x=80, y=270)
      vitarella = Label(janela, text="75(FD)").place(x=80, y=310)
  if pesquisa == "14003":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      nissin = Label(janela, text="Nissin Miojo Lámen 85g").place(x=80, y=150)
      nissin = Label(janela, text="R$ 1,01").place(x=80, y=190)
      nissin = Label(janela, text="R$ 30,30(CX/30)").place(x=80, y=230)
      nissin = Label(janela, text="Massa/Molho").place(x=80, y=270)
      nissin = Label(janela, text="34(CX)").place(x=80, y=310)
  if pesquisa == "14004":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      dona = Label(janela, text="Macarrão Pene Dona Benta 500g").place(x=80, y=150)
      dona = Label(janela, text="R$ 2,59").place(x=80, y=190)
      dona  = Label(janela, text="R$ 25,90(CX/10)").place(x=80, y=230)
      dona  = Label(janela, text="Massa/Molho").place(x=80, y=270)
      dona  = Label(janela, text="28(CX)").place(x=80, y=310)
  if pesquisa == "14005":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      brandini = Label(janela, text="Macarrão parafuso Brandini 500g").place(x=80, y=150)
      brandini = Label(janela, text="R$ 3,35").place(x=80, y=190)
      brandini = Label(janela, text="R$ 35,50(CX/10)").place(x=80, y=230)
      brandini = Label(janela, text="Massa/Molho").place(x=80, y=270)
      brandini = Label(janela, text="45(CX)").place(x=80, y=310)
  if pesquisa == "14006":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      quero = Label(janela, text="Molho de tomate Quero 340g").place(x=80, y=150)
      quero = Label(janela, text="R$ 1,49").place(x=80, y=190)
      quero = Label(janela, text="R$ 29,80(CX/20)").place(x=80, y=230)
      quero = Label(janela, text="Massa/Molho").place(x=80, y=270)
      quero = Label(janela, text="57(CX)").place(x=80, y=310)
  if pesquisa == "14007":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      pomodoro = Label(janela, text="Polpa de Tomate Pomodoro 520g").place(x=80, y=150)
      pomodoro = Label(janela, text="R$ 4,80").place(x=80, y=190)
      pomodoro = Label(janela, text="R$ 96,00(CX/20)").place(x=80, y=230)
      pomodoro = Label(janela, text="Massa/Molho").place(x=80, y=270)
      pomodoro = Label(janela, text="23(CX)").place(x=80, y=310)
  if pesquisa == "14008":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      hellmanns = Label(janela, text="Maionese hellmanns 500g").place(x=80, y=150)
      hellmanns = Label(janela, text="R$ 7,59").place(x=80, y=190)
      hellmanns = Label(janela, text="R$ 151,80 (CX/20)").place(x=80, y=230)
      hellmanns = Label(janela, text="Massa/Molho").place(x=80, y=270)
      hellmanns = Label(janela, text="37(CX)").place(x=80, y=310)
  if pesquisa == "14009":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      heinz = Label(janela, text="Ketchup Heinz 397g").place(x=80, y=150)
      heinz = Label(janela, text="R$ 9,79").place(x=80, y=190)
      heinz = Label(janela, text="R$ 195,80 (CX/20)").place(x=80, y=230)
      heinz = Label(janela, text="Massa/Molho").place(x=80, y=270)
      heinz = Label(janela, text="30(CX)").place(x=80, y=310)
  if pesquisa == "14010":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      heinz = Label(janela, text="Molho Shoyu Sakura 150ML").place(x=80, y=150)
      heinz = Label(janela, text="R$ 1,40").place(x=80, y=190)
      heinz = Label(janela, text="R$ 42,00 (CX/30)").place(x=80, y=230)
      heinz = Label(janela, text="Massa/Molho").place(x=80, y=270)
      heinz = Label(janela, text="27(CX)").place(x=80, y=310)
  if pesquisa == "15001":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      treloso = Label(janela, text="Biscoito Treloso Recheado 130g").place(x=80, y=150)
      treloso = Label(janela, text="R$ 1,89").place(x=80, y=190)
      treloso = Label(janela, text="R$ 37,80 (CX/20)").place(x=80, y=230)
      treloso = Label(janela, text="Bomboniere").place(x=80, y=270)
      treloso = Label(janela, text="120(CX)").place(x=80, y=310)
  if pesquisa == "15002":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      pira = Label(janela, text="Leite Condensado Piracanjuba 395g").place(x=80, y=150)
      pira = Label(janela, text="R$ 4,49").place(x=80, y=190)
      pira = Label(janela, text="R$ 112,25 (CX/25)").place(x=80, y=230)
      pira = Label(janela, text="Bomboniere").place(x=80, y=270)
      pira = Label(janela, text="75(CX)").place(x=80, y=310)
  if pesquisa == "15003":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      italac = Label(janela, text="Creme de Leite Italac 200g").place(x=80, y=150)
      italac = Label(janela, text="R$ 2,35").place(x=80, y=190)
      italac = Label(janela, text="R$ 70,50 (CX/30)").place(x=80, y=230)
      italac = Label(janela, text="Bomboniere").place(x=80, y=270)
      italac = Label(janela, text="95(CX)").place(x=80, y=310)
  if pesquisa == "15004":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      maizena = Label(janela, text="Biscoito Maizena Vitarella 400g").place(x=80, y=150)
      maizena = Label(janela, text="R$ 4,49").place(x=80, y=190)
      maizena = Label(janela, text="R$ 89,80 (CX/20)").place(x=80, y=230)
      maizena = Label(janela, text="Bomboniere").place(x=80, y=270)
      maizena = Label(janela, text="89(CX)").place(x=80, y=310)
  if pesquisa == "15005":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      pippos = Label(janela, text="Salgadinho Pippo's Vitaminado 150g").place(x=80, y=150)
      pippos = Label(janela, text="R$ 2,54").place(x=80, y=190)
      pippos = Label(janela, text="R$ 50,80 (FD/20)").place(x=80, y=230)
      pippos = Label(janela, text="Bomboniere").place(x=80, y=270)
      pippos = Label(janela, text="76(FD)").place(x=80, y=310)
  if pesquisa == "15006":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      kelloggs = Label(janela, text="Cereal Sucrilhos Kellogg's 730g").place(x=80, y=150)
      kelloggs = Label(janela, text="R$ 22,65").place(x=80, y=190)
      kelloggs = Label(janela, text="R$ 90,60 (CX/4)").place(x=80, y=230)
      kelloggs = Label(janela, text="Bomboniere").place(x=80, y=270)
      kelloggs = Label(janela, text="23(CX)").place(x=80, y=310)
  if pesquisa == "15007":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      camponesa = Label(janela, text="Leite em pó Camponesa 400g").place(x=80, y=150)
      camponesa = Label(janela, text="R$ 2,45").place(x=80, y=190)
      camponesa = Label(janela, text="R$ 49,00 (FD/20)").place(x=80, y=230)
      camponesa = Label(janela, text="Bomboniere").place(x=80, y=270)
      camponesa = Label(janela, text="54(FD)").place(x=80, y=310)
  if pesquisa == "15008":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      goiabada = Label(janela, text="Goiabada Predilecta 400g").place(x=80, y=150)
      goiabada = Label(janela, text="R$ 4,32").place(x=80, y=190)
      goiabada = Label(janela, text="R$ 64,80 (CX/15)").place(x=80, y=230)
      goiabada = Label(janela, text="Bomboniere").place(x=80, y=270)
      goiabada = Label(janela, text="45(CX)").place(x=80, y=310)
  if pesquisa == "15009":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      cafe = Label(janela, text="Café São Braz 250g").place(x=80, y=150)
      cafe = Label(janela, text="R$ 5,89").place(x=80, y=190)
      cafe = Label(janela, text="R$ 117,80 (FD/20)").place(x=80, y=230)
      cafe = Label(janela, text="Bomboniere").place(x=80, y=270)
      cafe = Label(janela, text="89(FD)").place(x=80, y=310)
  if pesquisa == "15010":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      sococo = Label(janela, text="Leite de Coco Sococo 200ML").place(x=80, y=150)
      sococo = Label(janela, text="R$ 3,39").place(x=80, y=190)
      sococo = Label(janela, text="R$ 84,75 (CX/25)").place(x=80, y=230)
      sococo = Label(janela, text="Bomboniere").place(x=80, y=270)
      sococo = Label(janela, text="25(CX)").place(x=80, y=310)
  if pesquisa == "16001":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      elite = Label(janela, text="Papel Higiênico Elite L16P15").place(x=80, y=150)
      elite = Label(janela, text="R$ 13,90").place(x=80, y=190)
      elite = Label(janela, text="R$ 139,00 (FD/10)").place(x=80, y=230)
      elite = Label(janela, text="Descartáveis").place(x=80, y=270)
      elite = Label(janela, text="50(FD)").place(x=80, y=310)
  if pesquisa == "16002":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      cafe = Label(janela, text="Papel Higiênico Personal L16P15").place(x=80, y=150)
      cafe = Label(janela, text="R$ 15,29").place(x=80, y=190)
      cafe = Label(janela, text="R$ 152,90 (FD/10)").place(x=80, y=230)
      cafe = Label(janela, text="Descartáveis").place(x=80, y=270)
      cafe = Label(janela, text="47(FD)").place(x=80, y=310)
  if pesquisa == "16003":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      assolan = Label(janela, text="Lã de Aço Assolan").place(x=80, y=150)
      assolan = Label(janela, text="R$ 1,67").place(x=80, y=190)
      assolan = Label(janela, text="R$ 33,40 (FD/20)").place(x=80, y=230)
      assolan = Label(janela, text="Descartáveis").place(x=80, y=270)
      assolan = Label(janela, text="39(FD)").place(x=80, y=310)
  if pesquisa == "16004":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      bombril = Label(janela, text="Lã de Aço Bombril").place(x=80, y=150)
      bombril = Label(janela, text="R$ 1,69").place(x=80, y=190)
      bombril = Label(janela, text="R$ 33,80 (FD/20)").place(x=80, y=230)
      bombril = Label(janela, text="Descartáveis").place(x=80, y=270)
      bombril = Label(janela, text="47(FD)").place(x=80, y=310)
  if pesquisa == "16005":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      balao = Label(janela, text="Balões de festa Látex 20UND").place(x=80, y=150)
      balao = Label(janela, text="R$ 14,15").place(x=80, y=190)
      balao = Label(janela, text="R$ 141,50 (CX/10)").place(x=80, y=230)
      balao = Label(janela, text="Descartáveis").place(x=80, y=270)
      balao = Label(janela, text="12(CX)").place(x=80, y=310)
  if pesquisa == "16006":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      perfex = Label(janela, text="Rolo Perfex Multiuso 50UND").place(x=80, y=150)
      perfex = Label(janela, text="R$ 14,90").place(x=80, y=190)
      perfex = Label(janela, text="R$ 149,00 (CX/10)").place(x=80, y=230)
      perfex = Label(janela, text="Descartáveis").place(x=80, y=270)
      perfex = Label(janela, text="14(CX)").place(x=80, y=310)
  if pesquisa == "16008":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      faca = Label(janela, text="Faca Descartável Sobremesas 50UND").place(x=80, y=150)
      faca = Label(janela, text="R$ 3,13").place(x=80, y=190)
      faca = Label(janela, text="R$ 93,90 (CX/30)").place(x=80, y=230)
      faca = Label(janela, text="Descartáveis").place(x=80, y=270)
      faca = Label(janela, text="19(CX)").place(x=80, y=310)
  if pesquisa == "16009":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      copo = Label(janela, text="Copo 300ML PCT 100UND").place(x=80, y=150)
      copo = Label(janela, text="R$ 2,60").place(x=80, y=190)
      copo = Label(janela, text="R$ 26,00 (CX/10)").place(x=80, y=230)
      copo = Label(janela, text="Descartáveis").place(x=80, y=270)
      copo = Label(janela, text="16(CX)").place(x=80, y=310)
  if pesquisa == "16010":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      faca = Label(janela, text="Cesto de Lixo").place(x=80, y=150)
      faca = Label(janela, text="R$ 98,00").place(x=80, y=190)
      faca = Label(janela, text="R$ 196,00 (CX/2)").place(x=80, y=230)
      faca = Label(janela, text="Descartáveis").place(x=80, y=270)
      faca = Label(janela, text="9(CX)").place(x=80, y=310)
  if pesquisa == "17001":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      manteiga = Label(janela, text="Margarina Delicia 500g").place(x=80, y=150)
      manteiga = Label(janela, text="R$ 5,39").place(x=80, y=190)
      manteiga = Label(janela, text="R$ 53,90 (CX/10)").place(x=80, y=230)
      manteiga = Label(janela, text="Frios").place(x=80, y=270)
      manteiga = Label(janela, text="56(CX)").place(x=80, y=310)
  if pesquisa == "17002":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      danone = Label(janela, text="Iogurte Danone Morango 1,35Kg").place(x=80, y=150)
      danone = Label(janela, text="R$ 11,00").place(x=80, y=190)
      danone = Label(janela, text="R$ 99,00 (CX/9)").place(x=80, y=230)
      danone = Label(janela, text="Frios").place(x=80, y=270)
      danone = Label(janela, text="45(CX)").place(x=80, y=310)
  if pesquisa == "17003":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      nestle = Label(janela, text="Iogurte Natural Nestlé 170g").place(x=80, y=150)
      nestle = Label(janela, text="R$ 2,49").place(x=80, y=190)
      nestle = Label(janela, text="R$ 29,88 (CX/12)").place(x=80, y=230)
      nestle = Label(janela, text="Frios").place(x=80, y=270)
      nestle = Label(janela, text="76(CX)").place(x=80, y=310)
  if pesquisa == "17004":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      hamburger = Label(janela, text="Hambúger Bovino Seara 12 UND").place(x=80, y=150)
      hamburger = Label(janela, text="R$ 21,00").place(x=80, y=190)
      hamburger = Label(janela, text="R$ 199,52 (CX/4)").place(x=80, y=230)
      hamburger = Label(janela, text="Frios").place(x=80, y=270)
      hamburger = Label(janela, text="34(CX)").place(x=80, y=310)
  if pesquisa == "17005":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      pizza = Label(janela, text="Pizza Sadia 460G").place(x=80, y=150)
      pizza = Label(janela, text="R$ 15,50").place(x=80, y=190)
      pizza = Label(janela, text="R$ 62,00 (CX/4)").place(x=80, y=230)
      pizza = Label(janela, text="Frios").place(x=80, y=270)
      pizza = Label(janela, text="20(CX)").place(x=80, y=310)
  if pesquisa == "17006":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      lasanha = Label(janela, text="Lasanha Seara 600g").place(x=80, y=150)
      lasanha = Label(janela, text="R$ 10,98").place(x=80, y=190)
      lasanha = Label(janela, text="R$ 109,80 (CX/10)").place(x=80, y=230)
      lasanha = Label(janela, text="Frios").place(x=80, y=270)
      lasanha = Label(janela, text="29(CX)").place(x=80, y=310)
  if pesquisa == "17007":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      requeijao = Label(janela, text="Requeijão Cremoso Vigor 200g").place(x=80, y=150)
      requeijao = Label(janela, text="R$ 10,98").place(x=80, y=190)
      requeijao = Label(janela, text="R$ 109,80 (CX/10)").place(x=80, y=230)
      requeijao = Label(janela, text="Frios").place(x=80, y=270)
      requeijao = Label(janela, text="45(CX)").place(x=80, y=310)
  if pesquisa == "17008":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      requeijao = Label(janela, text="Requeijão Cremoso Cheddar 200g").place(x=80, y=150)
      requeijao = Label(janela, text="R$ 7,39").place(x=80, y=190)
      requeijao = Label(janela, text="R$ 73,90 (CX/10)").place(x=80, y=230)
      requeijao = Label(janela, text="Frios").place(x=80, y=270)
      requeijao = Label(janela, text="47(CX)").place(x=80, y=310)
  if pesquisa == "17009":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      nuggets = Label(janela, text="Nuggets de Frango Sadia 300g").place(x=80, y=150)
      nuggets = Label(janela, text="R$ 7,39").place(x=80, y=190)
      nuggets = Label(janela, text="R$ 73,90 (CX/10)").place(x=80, y=230)
      nuggets = Label(janela, text="Frios").place(x=80, y=270)
      nuggets = Label(janela, text="37(CX)").place(x=80, y=310)
  if pesquisa == "17010":
      limpar = Label(janela, text="                                                            ").place(x=80, y=150)
      limpar = Label(janela, text="                                                            ").place(x=80, y=190)
      limpar = Label(janela, text="                                                            ").place(x=80, y=230)
      limpar = Label(janela, text="                                                            ").place(x=80, y=270)
      limpar = Label(janela, text="                                                            ").place(x=110, y=350)
      nuggets = Label(janela, text="Batata Bint Congelada 2Kg").place(x=80, y=150)
      nuggets = Label(janela, text="R$ 19,98").place(x=80, y=190)
      nuggets = Label(janela, text="R$ 79,92 (FD/4)").place(x=80, y=230)
      nuggets = Label(janela, text="Frios").place(x=80, y=270)
      nuggets = Label(janela, text="18(CX)").place(x=80, y=310)












bt = Button(janela, text="Pesquisar",command=pesquisa_produto).place(x=130,y=80)


janela.mainloop()
